services:
  - type: web
    name: college-bus-transport
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: college-bus-transport-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=75.0"

  - type: postgresql
    name: college-bus-transport-db
    plan: free
    ipAllowList: [] 